[WIP]Using hooks to implement ZeRO and Checkpoint
OpenBMB/BMTrain pull request #128
Opened 2023-07-24 05:51 UTC by zkh2016

2023-08-18 13:13 UTC, Achazwl commented on bmtrain/block_layer.py
> +            return tuple(post_out)
改成 post_out = tuple(post_out) 和下面共用 return

2023-08-19 06:49 UTC, Achazwl requested changes

2023-08-19 06:49 UTC, Achazwl commented on bmtrain/checkpointing.py
>  class ScopedDebugTensorList:
also for ScopedTensorInspectorContext in line 20

2023-08-19 06:49 UTC, Achazwl commented on bmtrain/pipe_layer.py
> +        ScopedTensorInspectorContext,
unused

2023-08-19 06:49 UTC, Achazwl commented on bmtrain/pipe_layer.py
> +            micro_hidden_states = []
send recv 改成 Op 放在这里，直接省去 hook_func 里的所有 pipe_pre_xx 和 pipe_post_xx

2023-08-21 01:31 UTC, Achazwl commented on bmtrain/block_layer.py
> +        assert len(self._next_module) == self._ref_count, "{} != {}".format(len(self._next_module), self._ref_count)
pre_module 需要 assert 吗

2023-08-21 02:50 UTC, zkh2016 commented on bmtrain/init.py
> +    for i in range(world_size):
deleted

2023-08-21 02:51 UTC, zkh2016 commented on bmtrain/init.py
> +    config["block_context"] = []
deleted

2023-08-21 02:51 UTC, zkh2016 commented on bmtrain/block_layer.py
> +        ScopedTensorInspectorContext,
done

2023-08-21 02:51 UTC, zkh2016 commented on bmtrain/block_layer.py
>  class CheckpointBlock(torch.nn.Module):
ok，下一个PR进行重命名

2023-08-21 03:17 UTC, zkh2016 commented on bmtrain/checkpointing.py
>  class ScopedDebugTensorList:
done

2023-08-21 03:17 UTC, zkh2016 commented on bmtrain/pipe_layer.py
> +        ScopedTensorInspectorContext,
done

2023-08-21 03:19 UTC, zkh2016 commented on bmtrain/block_layer.py
> +        assert len(self._next_module) == self._ref_count, "{} != {}".format(len(self._next_module), self._ref_count)
done

2023-08-21 03:19 UTC, zkh2016 commented on bmtrain/checkpointing.py
> +                if config['world_size'] > 1 and not self.block.all_input_no_grad:
deleted

2023-08-21 04:22 UTC, Achazwl approved these changes

2023-08-21 04:25 UTC, zkh2016 commented on bmtrain/__init__.py
> -    from . import nccl
已恢复

2023-08-21 04:36 UTC, Achazwl approved these changes

2023-08-21 07:12 UTC, Achazwl approved these changes

2023-08-21 07:13 UTC, merged