FIX Error: tensor slice in gather()
OpenBMB/BMTrain pull request #146
Opened 2023-08-18 08:25 UTC by JerryYin777

2023-08-18 13:38 UTC, MayDomine reviewed
The device needed for communication unit test should't be set to 1.

2023-08-19 04:34 UTC, Achazwl requested changes

2023-08-19 04:34 UTC, Achazwl commented on tests/test_synchronize.py
> +
需要手动构建 ref_result 做为参考值，并在代码里增加 assert 判断，避免用肉眼检查。比如说，让 tensor=torch.ones(5,5)*bmt.rank()。这样 gather_result 的期望结果比较容易构造出来

2023-08-19 04:34 UTC, Achazwl commented on tests/test_all.py
> +    ("synchronize", 1),
gather_result 的测试必须在多卡上才能完成，单卡上完全不会执行 gather

2023-08-28 06:31 UTC, Achazwl approved these changes

2023-08-28 06:32 UTC, merged