Add Reduce Scatter communication op.
OpenBMB/BMTrain pull request #147
Opened 2023-08-18 10:35 UTC by MayDomine

2023-08-19 04:29 UTC, Achazwl requested changes

2023-08-19 04:29 UTC, Achazwl commented on bmtrain/distributed/ops.py
> +        elif op in ["max", "min"]:
input output 的 dim 不一样

2023-08-19 04:29 UTC, Achazwl commented on bmtrain/distributed/ops.py
> +            grad_output = OpAllGather.apply(grad_output, ctx.comm).transpose(1, ctx.dim).flatten(0,1).transpose(0, ctx.dim)
第一个 transpose 应为 transpose(1, ctx.dim+1)

2023-08-19 04:29 UTC, Achazwl commented on tests/test_nccl_backward.py
> +    x = torch.ones((24,), dtype=torch.half, device="cuda").requires_grad_(True)
没有测多维

2023-08-19 04:29 UTC, Achazwl commented on tests/test_nccl_backward.py
> +    y = bmt.distributed.reduce_scatter(x, "sum")
dim!=0 和其他 op 类型也测一下

2023-08-19 04:29 UTC, Achazwl commented on tests/test_nccl_backward.py
> +    ref = torch.ones((24,), dtype=torch.half, device="cuda")
这种 ref 转不转置都没区别，拍不出问题

2023-08-19 04:29 UTC, Achazwl commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +
三个无关的 yml 文件

2023-08-21 11:40 UTC, Achazwl commented on bmtrain/distributed/ops.py
> +            raise NotImplementedError("max min operation now do not support backward")
max/min/prod ...  in ReduceScatter

2023-09-14 06:26 UTC, zkh2016 approved these changes

2023-09-14 06:27 UTC, merged