[WIP]Tensor Parallel
OpenBMB/BMTrain pull request #153
Opened 2023-08-23 11:37 UTC by zkh2016

2023-08-23 12:42 UTC, Achazwl commented on bmtrain/nn/__init__.py
> +from .cross_entropy import fused_cross_entropy
应该叫 Parallelxxx

2023-08-23 12:42 UTC, Achazwl commented on bmtrain/nn/embedding.py
> +            ids = all_gather(ids, comm=config['tp_comm'])
留一个 gather input 的接口

2023-08-23 12:51 UTC, Achazwl commented on bmtrain/param_init.py
> +from . import nccl
unused

2023-08-23 12:56 UTC, Achazwl commented on bmtrain/block_layer.py
> +                if not tp_mode and input_param.shape != it["shape"]:
tp mode 是不是也得加个什么 assert

2023-08-23 12:56 UTC, Achazwl commented on bmtrain/block_layer.py
> +                if not tp_mode:
同上

2023-08-23 12:59 UTC, Achazwl commented on bmtrain/init.py
> +        tp_size = 1,
: int

2023-08-23 13:37 UTC, Achazwl commented on bmtrain/init.py
> +            self.tp_zero_id = (self.dp_group == self.rank).nonzero()[0,2 if tp_size > 1 else 0].item()
这逻辑有点乱，是不是 tp=1 直接用 zero_id 和 zero_idx 就行了

2023-08-24 05:26 UTC, zkh2016 commented on bmtrain/nn/__init__.py
> +from .cross_entropy import fused_cross_entropy
done

2023-08-24 05:59 UTC, Achazwl requested changes

2023-08-24 05:59 UTC, Achazwl commented on bmtrain/init.py
>              self.tp_zero_idx = self.tp_id
tp_zero_idx = stage_id*tp_size+tp_id
tp_zero_id=pipe_idx // tp_size

2023-08-25 15:05 UTC, Achazwl commented on bmtrain/nn/parallel_linear_func.py
> +            grad_output_list = grad_output.chunk(tp_size, dim=1)
should be -1

2023-08-26 07:13 UTC, zkh2016 commented on bmtrain/nn/parallel_linear_func.py
> +            grad_output_list = grad_output.chunk(tp_size, dim=1)
done

2023-08-29 03:13 UTC, Achazwl approved these changes

2023-08-29 03:13 UTC, merged