Support the maximize parameter for adam when dtype is torch.half
OpenBMB/BMTrain pull request #35
Opened 2022-07-03 08:15 UTC by alphaGem

Related to [issue34](https://github.com/OpenBMB/BMTrain/issues/34)

2022-07-04 02:21 UTC, a710128 requested changes

2022-07-04 02:21 UTC, a710128 commented on bmtrain/optim/adam.py
> +                            grad = p.grad
`grad` was not passed to the adam function

2022-07-04 02:22 UTC, a710128 commented
1. AdamOffload needs to be updated.
https://github.com/OpenBMB/BMTrain/blob/0.1.7.post1/bmtrain/optim/adam_offload.py#L131-L172
2. The maximize parameter of torch.float also needs to be supported.
3. A bug: `grad` was not passed to the adam function.

2022-07-05 10:12 UTC, alphaGem commented
Update:
1. Adam Offload now updated.
2. Maximize parameter of torch.float now supported.
3. `grad` now passed to the adam function.

2022-07-07 04:52 UTC, a710128 approved these changes

2022-07-08 02:06 UTC, merged